/* LilAura Commerce Engine v2.0 */
(function(){
'use strict';
const CFG=window.LILAURA_CONFIG||{};
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
let DATA={items:[]};
let cart=JSON.parse(localStorage.getItem('lilaura_cart')||'[]');
let wishes=JSON.parse(localStorage.getItem('lilaura_wishlist')||'[]');

function header(){
 const mount=$('#site-header'); if(!mount)return;
 mount.innerHTML=`<a class="skip" href="#main">Skip to content</a><div class="announcement" id="promoBar">FREE UK DELIVERY · DISCOVER LILAURA</div><header class="site-header"><nav class="nav" aria-label="Primary"><button class="icon-btn mobile-toggle" id="mobileToggle" aria-label="Open menu">☰</button><div class="nav-links"><a href="/">Home</a><a href="/shop.html">Shop</a><a href="/heritage/">Heritage</a><a href="/everyday/">Everyday</a><a href="/journal/">Journal</a></div><a class="logo" href="/">LilAura<small>Elegance Made Eternal</small></a><div class="nav-actions"><a class="icon-btn" href="/contact.html" aria-label="Contact">Contact</a><button class="icon-btn" id="cartOpen" aria-label="Open shopping bag">Bag <span class="badge" id="cartCount">0</span></button></div></nav><div id="mobileMenu" style="display:none;border-top:1px solid var(--line);padding:18px 20px"><a href="/shop.html">Shop all</a><br><a href="/heritage/">Heritage</a><br><a href="/everyday/">Everyday</a><br><a href="/gifts/">Gifts</a><br><a href="/journal/">Journal</a></div></header>`;
 $('#mobileToggle')?.addEventListener('click',()=>{const m=$('#mobileMenu');m.style.display=m.style.display==='none'?'block':'none'});
 $('#cartOpen')?.addEventListener('click',openDrawer); updateCartCount();
}
function footer(){const m=$('#site-footer');if(!m)return;m.innerHTML=`<footer class="site-footer"><div class="footer-grid"><div><div class="footer-brand">LilAura</div><p style="color:#bdb4aa;max-width:300px">Indian heritage and modern everyday jewellery, curated in the UK.</p></div><div><h3>Shop</h3><a href="/shop.html">All jewellery</a><a href="/heritage/">Heritage</a><a href="/everyday/">Everyday</a><a href="/gifts/">Gifts</a></div><div><h3>Explore</h3><a href="/heritage/kerala-jewellery/">Kerala jewellery</a><a href="/heritage/palakka-jewellery/">Palakka jewellery</a><a href="/heritage/meenakari-jewellery/">Meenakari jewellery</a><a href="/everyday/anti-tarnish-jewellery/">Anti-tarnish jewellery</a></div><div><h3>Help</h3><a href="/care.html">Jewellery care</a><a href="/reviews.html">Reviews</a><a href="/concierge.html">Concierge</a><a href="/contact.html">Contact</a></div><div><h3>Legal</h3><a href="/policies.html#returns">Returns</a><a href="/policies.html#terms">Terms</a><a href="/privacy.html">Privacy</a><a href="https://www.etsy.com/uk/shop/LilauraElegance" rel="noopener">Etsy shop</a><a href="https://instagram.com/lilaura.uk" rel="noopener">Instagram</a></div></div><div class="copyright"><span>© ${new Date().getFullYear()} LilAura UK. All rights reserved.</span><span>Born in Britain · Inspired by India</span></div></footer><div class="drawer-overlay" id="drawerOverlay"></div><aside class="drawer" id="drawer" aria-label="Shopping bag"><div class="drawer-head"><strong>Your bag</strong><button class="icon-btn" id="drawerClose" aria-label="Close shopping bag">×</button></div><div id="cartItems"></div><div id="cartTotal" style="padding-top:18px;font-weight:600"></div><a class="btn dark" id="checkoutEtsy" style="width:100%;margin-top:15px" target="_blank" rel="noopener" href="${esc(CFG.etsy||'https://www.etsy.com/uk/shop/LilauraElegance')}">Checkout securely on Etsy</a><p class="legacy-note">Your purchase is completed through LilAura's Etsy storefront.</p></aside><div class="toast" id="toast"></div>`;$('#drawerClose').addEventListener('click',closeDrawer);$('#drawerOverlay').addEventListener('click',closeDrawer);renderCart();}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function save(){localStorage.setItem('lilaura_cart',JSON.stringify(cart));localStorage.setItem('lilaura_wishlist',JSON.stringify(wishes));updateCartCount();renderCart()}
function updateCartCount(){const n=$('#cartCount');if(n)n.textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openDrawer(){$('#drawer')?.classList.add('open');$('#drawerOverlay')?.classList.add('open')}
function closeDrawer(){$('#drawer')?.classList.remove('open');$('#drawerOverlay')?.classList.remove('open')}
function addToCart(id){const p=DATA.items.find(x=>x.id==id);if(!p||!p.inStock){toast('This piece is currently unavailable.');return}const x=cart.find(x=>x.id==id);x?x.qty++:cart.push({id:p.id,qty:1});save();openDrawer();toast('Added to your bag')}
function removeCart(id){cart=cart.filter(x=>x.id!=id);save();toast('Item removed from bag')}
function clearCart(){if(!cart.length)return;if(confirm('Are you sure you want to empty your bag?')){cart=[];save();toast('Bag has been emptied')}}
function toggleWish(id){const i=wishes.indexOf(Number(id));i>=0?wishes.splice(i,1):wishes.push(Number(id));save();renderProducts();toast(i>=0?'Removed from wishlist':'Saved to wishlist')}
function renderCart(){const box=$('#cartItems'),tot=$('#cartTotal');if(!box||!tot)return;if(!cart.length){box.innerHTML='<p style="padding:35px 0;color:var(--muted)">Your bag is waiting. Discover the collection.</p>';tot.textContent='';return}let total=0;box.innerHTML=cart.map(x=>{const p=DATA.items.find(y=>y.id==x.id);if(!p)return '';total+=p.price*x.qty;return `<div class="cart-item"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div><strong>${esc(p.name)}</strong><div>£${p.price.toFixed(2)} × ${x.qty}</div><button class="icon-btn" onclick="Lilaura.remove(${p.id})">Remove</button></div></div>`}).join('');tot.innerHTML='Subtotal £'+total.toFixed(2)+`<button class="icon-btn" style="display:block;margin-top:8px;padding-left:0;text-decoration:underline" onclick="Lilaura.clear()">Empty bag</button>`;const checkout=$('#checkoutEtsy');if(checkout){const one=cart.length===1?DATA.items.find(p=>p.id===cart[0].id):null;checkout.href=one?.etsyLink||CFG.etsy||'https://www.etsy.com/uk/shop/LilauraElegance'}}
function productCard(p){const saved=wishes.includes(Number(p.id));const label=p.world==='HERITAGE'?'Heritage':(p.inStock?'Everyday':'Currently unavailable');const hover=p.imageHover||'';const hoverVisual=hover.endsWith('.mp4')?`<video class="product-hover" src="${esc(hover)}" muted loop playsinline preload="metadata"></video>`:(hover?`<img class="product-hover" src="${esc(hover)}" alt="" loading="lazy">`:'');return `<article class="product-card"><a href="/products/${p.slug}/"><div class="product-media"><span class="product-badge">${label}</span><button class="wish" type="button" aria-label="${saved?'Remove':'Save'} ${esc(p.name)}" onclick="event.preventDefault();event.stopPropagation();Lilaura.wish(${p.id})">${saved?'♥':'♡'}</button><img class="product-base" src="${esc(p.image)}" alt="${esc(p.name)} by LilAura" loading="lazy">${hoverVisual}<div class="quickbar"><span class="quick">Quick view</span>${p.inStock?`<button class="quick add" onclick="event.preventDefault();event.stopPropagation();Lilaura.add(${p.id})">Add to bag</button>`:''}</div></div><div class="product-copy"><div class="product-meta">${esc(p.category)}</div><div class="product-name">${esc(p.name)}</div><div class="price">£${Number(p.price).toFixed(2)}</div></div></a></article>`}
function renderProducts(){const grid=$('#productGrid');if(!grid)return;const q=($('#productSearch')?.value||'').toLowerCase().trim();const active=$('.filterbar button.active')?.dataset.filter||'all';let list=DATA.items.filter(p=>{const matchesQ=!q||(p.name+' '+p.desc+' '+p.category).toLowerCase().includes(q);const matches=active==='all'||(active==='heritage'&&p.world==='HERITAGE')||(active==='everyday'&&p.world==='EVERYDAY')||(active==='necklaces'&&/necklace|choker/i.test(p.category+' '+p.name))||(active==='earrings'&&/earring|stud|hoop/i.test(p.category+' '+p.name))||(active==='cuffs'&&/cuff|bangle|kada/i.test(p.category+' '+p.name));return matchesQ&&matches});grid.innerHTML=list.map(productCard).join('');const count=$('#resultCount');if(count)count.textContent=`${list.length} pieces`}
function applyPromo(p){const bar=$('#promoBar');if(!bar)return;const c=p||{};if(!c.enabled){bar.style.display='none';return}bar.style.display='block';bar.innerHTML=`<span>${esc(c.title||'LilAura Edit')}</span> · ${esc(c.discountText||'Discover the latest edit')} <span id="promoTimer"></span>`;const end=new Date(c.endTime||'').getTime();if(!end||Number.isNaN(end)){return}const tick=()=>{const d=Math.max(0,end-Date.now());const total=Math.floor(d/1000);if(total<=0){bar.innerHTML=`<span>${esc(c.title||'LilAura Edit')}</span> · Offer ended`;return}const days=Math.floor(total/86400);const h=Math.floor(total%86400/3600);const m=Math.floor(total%3600/60);const sec=total%60;const x=$('#promoTimer');if(x)x.textContent=` · ${days}d ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m ${String(sec).padStart(2,'0')}s`};tick();clearInterval(window.__lilauraPromoTimer);window.__lilauraPromoTimer=setInterval(tick,1000)}
async function loadData(){try{DATA=await fetch('/products.json',{cache:'no-store'}).then(r=>r.json())}catch(e){console.error(e);return}applyPromo(DATA.promoConfig);renderProducts();renderCart();}
function productSEO(p){document.title=(p.seoTitle||p.name+' | LilAura UK');const d=document.querySelector('meta[name="description"]');if(d)d.content=p.metaDesc||p.desc;const can=document.querySelector('link[rel="canonical"]');if(can)can.href=location.href;}
function initShop(){if(!$('#productGrid'))return;$$('.filterbar button').forEach(b=>b.addEventListener('click',()=>{$$('.filterbar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()}));$('#productSearch')?.addEventListener('input',renderProducts);}
function initPDP(){const root=$('[data-product-id]');if(!root)return;const id=Number(root.dataset.productId);const p=DATA.items.find(x=>x.id===id);if(!p)return;productSEO(p);root.querySelector('[data-name]').textContent=p.name;root.querySelector('[data-price]').textContent='£'+Number(p.price).toFixed(2);root.querySelector('[data-category]').textContent=p.world==='HERITAGE'?'HERITAGE · '+p.category:'EVERYDAY · '+p.category;root.querySelector('[data-description]').textContent=p.desc;root.querySelector('[data-material]').textContent=p.material;root.querySelector('[data-sku]').textContent=p.sku;const img=root.querySelector('[data-main-image]');img.src=p.image;img.alt=p.name+' by LilAura';const claims=root.querySelector('[data-claims]');const flags=p.claims;claims.innerHTML=`<span class="claim ${flags.anti_tarnish?'':'no'}">${flags.anti_tarnish?'✓':'—'} Anti-tarnish</span><span class="claim ${flags.pvd?'':'no'}">${flags.pvd?'✓':'—'} 18K PVD</span><span class="claim ${flags.waterproof?'':'no'}">${flags.waterproof?'✓':'—'} Waterproof</span><span class="claim ${flags.water_resistant?'':'no'}">${flags.water_resistant?'✓':'—'} Water-resistant</span>`;const cta=root.querySelector('[data-buy]');if(!p.inStock){cta.textContent='Currently unavailable';cta.disabled=true}else{cta.addEventListener('click',()=>addToCart(p.id))}const etsy=root.querySelector('[data-etsy]');etsy.href=p.etsyLink;const related=DATA.items.filter(x=>x.id!==p.id&&x.world===p.world).slice(0,4);const rg=$('#relatedGrid');if(rg)rg.innerHTML=related.map(productCard).join('');const gm=root.querySelector('.gallery-main');if(gm&&p.imageHover){gm.onclick=()=>gm.classList.toggle('show-secondary')}}
window.Lilaura={add:addToCart,remove:removeCart,clear:clearCart,wish:toggleWish,open:openDrawer};
header();footer();
loadData().then(()=>{initShop();initPDP();renderRecent()});
})();
